### ISSUE TITLE
struct.error: unpack requires a buffer of 2 bytes

### ISSUE THREAD

**Issue by boredazfcuk** [icloud-photos-downloader/icloud_photos_downloader#411] opened 2022-02-21 19:32 UTC
## Overview
I've had a couple of users report a crash with the error in this issue's subject:

I see that it has previously been resolved and closed, but the resolution seems unrelated to the potential issue:

https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/113

The two users reported these errors in the accompanying issue threads:
https://github.com/boredazfcuk/docker-icloudpd/issues/138:
```
File "/usr/bin/icloudpd", line 33, in
sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in call
return self.main(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 562, in main
download_photo(consecutive_files_found, item)
File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 489, in download_photo
(".jpg", ".jpeg")) and not exif_datetime.get_photo_exif(download_path):
File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/exif_datetime.py", line 11, in get_photo_exif
exif_dict = piexif.load(path)
File "/usr/lib/python3.8/site-packages/piexif/_load.py", line 49, in load
exif_dict["Interop"] = exifReader.get_ifd_dict(pointer, "Interop")
File "/usr/lib/python3.8/site-packages/piexif/_load.py", line 108, in get_ifd_dict
tag_count = struct.unpack(self.endian_mark + "H",
struct.error: unpack requires a buffer of 2 bytes
```

and also https://github.com/boredazfcuk/docker-icloudpd/issues/125:
```
2022-01-31 17:14:06 INFO     Next synchronisation at 15:42:29
2022-01-31 17:14:06 INFO     Total time taken: 01:31:37
2022-01-31 17:14:06 INFO     Synchronisation ended at 17:14:06
2022-01-31 17:14:06 INFO     iCloud login counter = 2
2022-01-31 17:14:06 INFO     Days remaining until expiration: 83
2022-01-31 17:14:06 INFO     Two factor authentication cookie expires: 2022-04-24 @ 23:40:09
2022-01-31 17:14:06 INFO     Web cookie expires: 2022-03-25 @ 23:39:53
2022-01-31 17:14:06 ERROR    Error during download - Exit code: 1
struct.error: unpack requires a buffer of 2 bytes
tag_count = struct.unpack(self.endian_mark + "H",
File "/usr/lib/python3.8/site-packages/piexif/_load.py", line 108, in get_ifd_dict
exif_dict["Interop"] = exifReader.get_ifd_dict(pointer, "Interop")
File "/usr/lib/python3.8/site-packages/piexif/_load.py", line 49, in load
exif_dict = piexif.load(path)
File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/exif_datetime.py", line 11, in get_photo_exif
(".jpg", ".jpeg")) and not exif_datetime.get_photo_exif(download_path):
File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 489, in download_photo
download_photo(consecutive_files_found, item)
File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 562, in main
return callback(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
rv = self.invoke(ctx)
File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
return self.main(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
File "/usr/bin/icloudpd", line 33, in <module>
Traceback (most recent call last):
```

## Steps to Reproduce
Unknown.
It seems that this error is only being encountered when the `--setexif-datetime` option is being used. If this option is removed, the download will successfully complete. One user has then had success re-enabling this feature. It seems that when a file is downloaded, if the `--set-exif-datetime` argument is specified, the script crashes out. It would suggest that the EXIF date information is being read during the download and that some photos in the stream are being created with either corrupted values in the EXIF tag, or possibly that the EXIF tag does not exist in the file at all.

## Expected Behavior
That if corrupted values, or missing tags are encountered, the script skips over them.

## Actual Behavior
Script crashes with the errors above.

**Comment by AndreyNikiforov** [comment] 2023-02-04 01:31
@boredazfcuk I am wondering if 1.8.0+ works better (because it updated dependencies)?

**Comment by AndreyNikiforov** [comment] 2023-02-11 18:06
Traces point to piexif library source code. Same problem mentioned in the [original pkg](https://github.com/hMatoba/Piexif/issues/129) with no action. I see options:
- fork that project into this org/project and fix it
- use another lib

Either of these approaches require reliable steps to reproduce the problem. Closing until we have steps to repro (possibly image that causes piexif to fail).

**Closed by AndreyNikiforov** 2023-02-11 18:06 UTC
Labels: bug

**Comment by iamcalledrob** [comment] 2026-01-03 13:49
@AndreyNikiforov 

I've been running into this issue.

Each time, I get the following error:
```
Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "icloudpd/cli.py", line 609, in cli
  File "icloudpd/base.py", line 261, in run_with_configs
  File "icloudpd/base.py", line 438, in _process_all_users_once
  File "icloudpd/base.py", line 1084, in core_single_run
  File "icloudpd/base.py", line 716, in download_builder
  File "icloudpd/exif_datetime.py", line 13, in get_photo_exif
  File "piexif/_load.py", line 46, in load
  File "piexif/_load.py", line 129, in get_ifd_dict
  File "piexif/_load.py", line 149, in convert_value
struct.error: unpack requires a buffer of 320 bytes
[PYI-1057184:ERROR] Failed to execute script 'icloudpd' due to unhandled exception!
```

The photo gets downloaded, so re-running skips over the failed image until the next one is encountered.

I've attached 2 images that triggered this failure, zipped to ensure no mangling. These photos are unusual in that I didn't take them, they were downloaded email attachments, originally taken on an Android phone. Hopefully this is a reproducer?

[20200714_15.zip](https://github.com/user-attachments/files/24415917/20200714_15.zip)
