### ISSUE TITLE
Specify file names possibility

### ISSUE THREAD

**Issue by ronbruins** [icloud-photos-downloader/icloud_photos_downloader#500] opened 2022-11-17 12:39 UTC
I’m using icloudpd to download photos to my NAS and photoprism to make an album of it. Works great, except for the following:

icloudpd downloads Live Photos as following:
IMG_1234.HEIC / IMG_1234_HEVC.MOV

photoprism sees this as two separate times and doesn’t combine it into a Live Photo. My workaround is to copy all to IMG_1234.MOV so they match and ignore the HEVC in photoprism. However now I end up with twice the files. 

Is there a way to include an option to have both the files be named identical, except for different extensions obviously.

**Comment by Soulplayer** [comment] 2023-09-03 11:21
I'm having the same issue... This would be awesome to add!

**Comment by dtlics** [comment] 2024-03-21 23:20
If one downloaded the "original" version via iCloud API, xxx.HEIC and xxx.MOV is the files one gets, not sure why icloudpd decides to name is as xxx.HEIC and xxx_HEVC.MOV, this makes it complicated when one wants to use other iCloud functions based on the icloudpd results. What I do is I icloudpd once then do renaming via codes, then I have to stop using icloupd because it'll mess up the files

**Comment by dtlics** [comment] 2024-03-21 23:22
would really appreciate it if icloudpd can get this corrected. I don't wanna fork my own icloudpd and do this cause I expect future versions of icloudpd will be needed when icloud updates its APIs...

**Comment by AndreyNikiforov** [comment] 2024-03-22 01:17
> would really appreciate it if icloudpd can get this corrected

That is not a bug. icloudpd adds extension of the image to the name of the video file for live photos. Without that you can have live photo and regular video competing for the name with .MOV extension. Example:
- Live Photo Image1234 will be saved as a pair: Image1234.HEIC & Image1234_HEIC.MOV
- Video Asset Image1234.MOV will be saved as Image1234.MOV without conflict

**Comment by dtlics** [comment] 2024-03-22 01:38
would iPhone generate xxx.HEIC and xxx.MOV? it seems my iPhone would do something like IMG_0118.HEIC and then if i shoot a video it'll be IMG_0119.MOV, it increments the number by 1 automatically. I'm afraid worrying too much about avoiding duplicates adds too much complexity to using the tool with other softwares... I'd love to hear how your team think about this

**Comment by AndreyNikiforov** [comment] 2024-03-22 02:22
> would iPhone generate xxx.HEIC and xxx.MOV? it seems my iPhone would do something like IMG_0118.HEIC and then if i shoot a video it'll be IMG_0119.MOV, it increments the number by 1 automatically. I'm afraid worrying too much about avoiding duplicates adds too much complexity to using the tool with other softwares... I'd love to hear how your team think about this

Duplicate management needed for resolving updates over existing storage (to avoid re-downloading) as well. If you think it is worth supporting the case without _HEIC suffix for movies in live photos, feel free to write down expected behavior for all cases and then implement under its own flag.

**Comment by AndreyNikiforov** [comment] 2024-05-28 05:39
added to 1.18.0

**Closed by AndreyNikiforov** 2024-05-28 05:39 UTC
Labels: enhancement
