### ISSUE TITLE
[MacOS] Unknown reason authentication error

### ISSUE THREAD

**Issue by Brett-StrayThought** [icloud-photos-downloader/icloud_photos_downloader#700] opened 2023-10-03 08:44 UTC
## Overview
I previously used icloudpd without issue. I copied/pasted the command I used last time (don't know which version) that worked but it doesn't work this time in 1.16.2. It fails trying to login with 2FA. I tried many times, and manually logged into iCloud to be sure username and password are indeed correct.

Note in the error it says "Failed to send two-factor authentication code" however I received the SMS and also every one of my Apple devices prompted me asking to Allow/Deny too.

## Steps to Reproduce
1. Run "icloudpd --directory /Users/brett/Downloads/iPhoneImport/Brett --username <my username>@icloud.com --password <my password> --recent 1340 --set-exif-datetime --folder-structure {:%Y/%m}"
2. Results in error:
```
MBP iPhone Import$ icloudpd --directory /Users/brett/Downloads/iPhoneImport/Brett --username <my username>@icloud.com --password <my password> --recent 1340 --set-exif-datetime --folder-structure {:%Y/%m}
2023-10-03 10:31:22 DEBUG    Authenticating...
2023-10-03 10:31:23 INFO     Two-step/two-factor authentication is required
  0: SMS to ********10
  1: Enter two-factor authentication code
Please choose an option: [0]: Usage: icloudpd <options>
Try 'icloudpd -h' for help.

Error: No such option: -B

2023-10-03 10:31:59 ERROR    Failed to send two-factor authentication code
multiprocessing/resource_tracker.py:104: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
MBP iPhone Import$ Usage: icloudpd <options>
Try 'icloudpd -h' for help.

Error: No such option: -B

MBP iPhone Import$ 
```
## Expected Behavior
Expected it would work, or give a better reason for failure. Especially unsure what the "Error: No such option: -B" that pops up means.

## Actual Behavior
Didn't work

**Comment by boredazfcuk** [comment] 2023-10-03 09:01
Does your password have a -B in it by any chance?

**Comment by Brett-StrayThought** [comment] 2023-10-03 09:24
Good question! But it does not. It doesn't contain anything other than letters/numbers. Same for username.

**Comment by Brett-StrayThought** [comment] 2023-10-03 09:25
I did some Googling, and the "Error: No such option: -B" is odd and I could only find one other person who mentioned it.

https://www.mactechnews.de/journals/entry/iCloud-Mediathek-exportieren-und-Originale-sichern-1046.html

**Comment by MrChad0815** [comment] 2023-10-03 13:10
To the best of my knowledge, the ever-repeating misleading message

| Usage: icloudpd <options>
| Try 'icloudpd -h' for help.
| 
| Error: No such option: -B

appears on Apple Silicon machines (only?) and has no other negative effects

It is somehow caused by the interaction of the Python runtime system (multiprocessing libraries) and Apple's Rosetta machine code translation. 
The Python runtime system seems to believe the program has crashed and tries to restart it with some strange arguments "-B" and a few others others.

**Comment by Brett-StrayThought** [comment] 2023-10-03 13:32
Interesting. I'm on an Intel MacBook Pro so I don't think in this case it could be that.

**Comment by Brett-StrayThought** [comment] 2023-10-04 08:58
I went back to the original repo for pyicloud and found it works fine with no errors or the strange "not option -B" error. So before moving on, summary is:
* When 2FA is enabled (which is now enabled by default and once enabled can't be disabled), there are exceptions that occur which aren't handled and don't produce very good error reporting. Ideally this would be improved.
* There is a strange spurious "Error: No such option: -B" that occurs which doesn't occur in the original pyicloud implementation.

**Comment by alixmartineau** [comment] 2023-10-04 11:09
I have had the same problem for a while (icloudpd, version 1.14.5 on Apple M2 Pro)

```
$ icloudpd --directory 'Photos' --username 'xxx@xxx.xxx' --auto-delete
2023-10-04 12:57:08 DEBUG    Authenticating...
iCloud Password: 
2023-10-04 12:57:18 DEBUG    Looking up all photos and videos from album All Photos...
2023-10-04 12:57:18 INFO     Downloading 5002 original photos and videos to Photos ...
  0%|                                                                                                  | 0/5002 [00:00<?, ?it/s]Usage: icloudpd <options>
Try 'icloudpd -h' for help.

Error: No such option: -B
Photos/2014/12/24/IMG_0062.JPG already exists.: 100%|#######################################| 5002/5002 [05:22<00:00, 15.53it/s]2023-10-04 13:02:41 INFO     All photos have been downloaded!
2023-10-04 13:02:41 INFO     Deleting any files found in 'Recently Deleted'...
multiprocessing/resource_tracker.py:104: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.

Usage: icloudpd <options>
Try 'icloudpd -h' for help.

Error: No such option: -B
```

**Comment by flappah** [comment] 2023-10-27 19:38
I think it has to do with the existence of security keys in the apple-id. I had a similar error and after removing both security keys from my apple-id icloudpd worked again.

**Comment by asriraman** [comment] 2023-11-18 16:57
+1 with this issue (icloudpd, version 1.16.2), Apple M2

**Comment by juju4** [comment] 2023-11-19 16:06
> I think it has to do with the existence of security keys in the apple-id. I had a similar error and after removing both security keys from my apple-id icloudpd worked again.

Any plan to support security keys (FIDO2/webauthn)?
It seems that when configured, OTP is not available anymore. Also security keys configuration remove existing MFA sessions. Tested with icloudpd 1.16.2. Need to remove them to use OTP again.

https://support.apple.com/en-ca/guide/iphone/iph5acc5b28c/ios
"Note: If you remove all security keys from a device, the device reverts to using six-digit verification codes for two-factor authentication."

**Comment by gaffneyd4** [comment] 2023-11-25 13:32
If this error is caused by FIDO security keys being enabled as the 2FA method on the icloud account, then we can close this issue in favor of #583

**Comment by alixmartineau** [comment] 2023-11-25 17:23
It’s not linked. I have never had FIDO 2FA enabled on my account. Le 25 nov. 2023 à 14:33, Derek Gaffney ***@***.***> a écrit :﻿
If this error is caused by FIDO security keys being enabled as the 2FA method on the icloud account, then we can close this issue in favor of #583

**Comment by tooluser** [comment] 2023-12-21 18:10
I have the same issue on my Intel Mac mini, v 1.16.2, no FIDO security key.

**Comment by AndreyNikiforov** [comment] 2023-12-21 20:36
> I have the same issue on my Intel Mac mini, v 1.16.2, no FIDO security key.

Upgrade to 1.17.1. Versions prior to 1.17.0 stoped working recently due to changes in Apple API, See #729

**Closed by AndreyNikiforov** 2023-12-21 20:36 UTC
Labels: bug
