### ISSUE TITLE
icloudpd 1.17.3: Unhandled Exception While Authenticating

### ISSUE THREAD

**Issue by scrutinizer11** [icloud-photos-downloader/icloud_photos_downloader#772] opened 2024-01-08 01:31 UTC
## Overview

Upon entering my password the utility returned an exception.

## Steps to Reproduce:
1. Run **icloudpd** with any options.
2. Fulfill the authentication sequence.

## Expected Behavior:

Standard behavior.

## Actual Behavior

The exception is raised. It prevents me from normal use of this utility.

## Context
The context in which the exception occurred was macOS 10.9 with proxy server installed. Version 1.16 was able to bring me past the auth wall in this operating system. Perhaps, an additional option of proxy-routing could be included in the list of considerations. The debugging output of the trapped error is in the picture.

![image](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/45983734/0afb7f1f-5cd7-48f7-8684-3ce710da29dc)

**Comment by AndreyNikiforov** [comment] 2024-01-08 03:37
How is proxy configured for icloudpd process? Does icloudpd without proxy, pls?

**Comment by scrutinizer11** [comment] 2024-01-08 11:41
The proxy (Squid-based) has no per-app config options. It receives connections on **localhost:3128**. I also use Adguard's resolvers. When troubleshooting, I changed those to Google's but that had no difference. In fact, I doubt **icloudpd** connects to the Internet. _Little Snitch Network Monitor_ shows no traces of the outbound connections by **icloudpd**, so I don't see any cues allowing me to register its attempts at network activity.

**Comment by AndreyNikiforov** [comment] 2024-01-09 20:41
I am thinking of the following steps to troubleshoot:
- try prev version to isolate the change
- try without proxy to confirm that no other issues are inflicting proxy errors
- use HTTP_PROXY env var as mentioned in the [doc](https://docs.python.org/3/library/urllib.request.html#urllib.request.getproxies)
- try modifying src code for explicit proxy setup (at least to confirm that as a mitigation)

**Comment by rorymurtagh** [comment] 2024-01-09 21:06
I have the same issue. But no proxy. 1.17.2 works. latest/1.17.3 does not. Will keep looking/debug.

**Comment by SnoopyCoder** [comment] 2024-01-30 13:37
Same issue, Internet access is working (checked with "`curl www.google.com`") and no proxy.

```
2024-01-30 14:33:28 DEBUG    Authenticating...
2024-01-30 14:33:29 ERROR    Unknown reason
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 220, in authenticate
  File "requests/sessions.py", line 637, in post
  File "pyicloud_ipd/base.py", line 105, in request
  File "pyicloud_ipd/base.py", line 127, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 5, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 317, in main
  File "icloudpd/base.py", line 744, in core
  File "icloudpd/authentication.py", line 31, in authenticate_
  File "pyicloud_ipd/base.py", line 204, in __init__
  File "pyicloud_ipd/base.py", line 228, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
```

**Comment by axscrew** [comment] 2024-02-10 08:00
Almost same here so I'm not starting a new issue. The internet is working, nothing like proxy is meddling. Upon executing icloudpd prompts that Two-step/two-factor authentication is required (2fa) but none of my apple devices prompts me with the code. If I go to the settings -> Sign-In & Security > Two Factor Authentication -> Get Verification Code and enter the code, icloudpd fails. Initially 1.17.0 failed, I upgraded it to 1.17.2 (the latest windows build available) but this didn't help.


```
C:\Users\xscre\OneDrive\iCloud>C:\Users\xscre\OneDrive\iCloud\\icloudpd\icloudpd-1.17.2-windows-amd64.exe --username ******@gmail.com --directory C:\Users\xscre\OneDrive\iCloud\\Alex
2024-02-10 07:53:37 DEBUG    Authenticating...
2024-02-10 07:53:38 INFO     Two-step/two-factor authentication is required (2fa)
Please enter two-factor authentication code: 913897
2024-02-10 07:53:50 ERROR     (403)
Traceback (most recent call last):
  File "starters\icloudpd.py", line 6, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "icloudpd\base.py", line 328, in main
  File "icloudpd\base.py", line 760, in core
  File "icloudpd\authentication.py", line 48, in authenticate_
  File "icloudpd\authentication.py", line 105, in request_2fa
  File "pyicloud_ipd\base.py", line 539, in validate_2fa_code
  File "requests\sessions.py", line 637, in post
  File "pyicloud_ipd\base.py", line 134, in request
  File "pyicloud_ipd\base.py", line 207, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException:  (403)
[15196] Failed to execute script 'icloudpd' due to unhandled exception!

C:\Users\xscre\OneDrive\iCloud>PAUSE
Press any key to continue . . .
```

**Comment by axscrew** [comment] 2024-02-12 11:01
> Almost same here so I'm not starting a new issue. The internet is working, nothing like proxy is meddling. Upon executing icloudpd prompts that Two-step/two-factor authentication is required (2fa) but none of my apple devices prompts me with the code. If I go to the settings -> Sign-In & Security > Two Factor Authentication -> Get Verification Code and enter the code, icloudpd fails. Initially 1.17.0 failed, I upgraded it to 1.17.2 (the latest windows build available) but this didn't help.
> 
> ```
> C:\Users\xscre\OneDrive\iCloud>C:\Users\xscre\OneDrive\iCloud\\icloudpd\icloudpd-1.17.2-windows-amd64.exe --username ******@gmail.com --directory C:\Users\xscre\OneDrive\iCloud\\Alex
> 2024-02-10 07:53:37 DEBUG    Authenticating...
> 2024-02-10 07:53:38 INFO     Two-step/two-factor authentication is required (2fa)
> Please enter two-factor authentication code: 913897
> 2024-02-10 07:53:50 ERROR     (403)
> Traceback (most recent call last):
>   File "starters\icloudpd.py", line 6, in <module>
>   File "click\core.py", line 1157, in __call__
>   File "click\core.py", line 1078, in main
>   File "click\core.py", line 1434, in invoke
>   File "click\core.py", line 783, in invoke
>   File "icloudpd\base.py", line 328, in main
>   File "icloudpd\base.py", line 760, in core
>   File "icloudpd\authentication.py", line 48, in authenticate_
>   File "icloudpd\authentication.py", line 105, in request_2fa
>   File "pyicloud_ipd\base.py", line 539, in validate_2fa_code
>   File "requests\sessions.py", line 637, in post
>   File "pyicloud_ipd\base.py", line 134, in request
>   File "pyicloud_ipd\base.py", line 207, in _raise_error
> pyicloud_ipd.exceptions.PyiCloudAPIResponseException:  (403)
> [15196] Failed to execute script 'icloudpd' due to unhandled exception!
> 
> C:\Users\xscre\OneDrive\iCloud>PAUSE
> Press any key to continue . . .
> ```

What helped was deleting all auth-related files from `.pycloud` dir. Then I was prompted with the code which I hadn't been before.

**Comment by Mintume** [comment] 2024-02-16 09:06
Facing the same issue.

**Comment by Mintume** [comment] 2024-02-17 14:56
> What helped was deleting all auth-related files from `.pycloud` dir. Then I was prompted with the code which I hadn't been before.
Can you tell me the directory location and which file to be deleted, pls?

**Comment by axscrew** [comment] 2024-02-18 05:05
> > What helped was deleting all auth-related files from `.pycloud` dir. Then I was prompted with the code which I hadn't been before.
> > Can you tell me the directory location and which file to be deleted, pls?

I have windows, so I deleted all the files in this directory: `C:\Users\%USERNAME%\.pyicloud` Not sure about other OS.

**Comment by AndreyNikiforov** [comment] 2024-05-29 22:48
@scrutinizer11 do you still have an issue? Is it reproducible with latest version as well?

**Comment by axscrew** [comment] 2024-05-30 09:57
I can speak for myself. The issue hasn't surfaced since I deleted auth files. The latest version (1.18) works fine as well. I was prompted with a new code which I entered and it started download.

**Comment by AndreyNikiforov** [comment] 2024-05-30 16:31
resolved by removing `.pycloud` folder. [Updated FAQ](https://github.com/icloud-photos-downloader/icloud_photos_downloader/blob/master/FAQ.md#occasional-errors)

**Closed by AndreyNikiforov** 2024-05-30 16:31 UTC
Labels: bug
