### ISSUE TITLE
IOError while writing to file. You might have run out of disk space, or file might be too large for your OS

### ISSUE THREAD

**Issue by HarrisonOates** [icloud-photos-downloader/icloud_photos_downloader#155] opened 2020-06-16 20:56 UTC
I've run the script through once, and it worked alright, however it did not download all of the photos. I am getting the error 
`OError while writing file to #### You might have run out of disk space, or the file might be too large for your OS. Skipping this file...`
I'm on an Arch Linux machine.

**Comment by nihelmasell** [comment] 2020-09-14 07:53
I have the same issue.

**Comment by Monsterbacke007** [comment] 2020-10-04 20:09
I have the same issue: OS Win10 Pro trying to download onto a network drive (NAS).

**Comment by AndreyNikiforov** [comment] 2020-10-05 04:11
@LoonyGryphon @Monsterbacke007 assuming that disk has enough space for the file (and destination system supports large files), do you mind trying the process again? Since it was skipped during the error, next run will try to download it again and we'll see if the problem is specific to the file or intermittent.

**Comment by nihelmasell** [comment] 2020-10-05 05:19
I used this solution https://github.com/ndbroadbent/icloud_photos_downloader/issues/150#issuecomment-699099138 because I also had the issue mentioned in that thread. After doing that, I didn't have this problem again (it "magically" solved two issues at once).

**Comment by Monsterbacke007** [comment] 2020-10-05 07:17
@nihelmasell I am getting a syntax error trying this on Win10 Pro: As I am new to Python can someone please help?

`@property
    def albums(self):
        if not self._albums:
            self._albums = {name: PhotoAlbum(self, name, **props)
                            for (name, props) in self.SMART_FOLDERS.items()}

            for folder in self._fetch_folders():
                # FIXME: Handle subfolders
                if folder['recordName'] in ('----Root-Folder----',
                    '----Project-Root-Folder----') or \
                    (folder['fields'].get('isDeleted') and
                     folder['fields']['isDeleted']['value']):
                    continue

                folder_id = folder['recordName']
                folder_obj_type = \
                    "CPLContainerRelationNotDeletedByAssetDate:%s" % folder_id
                folder_name = base64.b64decode(
            try:
                folder['fields']['albumNameEnc']['value']).decode('utf-8')
            except KeyError:
                continue
            
                query_filter = [{
                    "fieldName": "parentId",
                    "comparator": "EQUALS",
                    "fieldValue": {
                        "type": "STRING",
                        "value": folder_id
                    }
                }]

                album = PhotoAlbum(self, folder_name,
                                   'CPLContainerRelationLiveByAssetDate',
                                   folder_obj_type, 'ASCENDING', query_filter)
                self._albums[folder_name] = album`

**Comment by nihelmasell** [comment] 2020-10-06 04:51
> @nihelmasell I am getting a syntax error or "continue not properly in loop" trying this on Win10 Pro: As I am new to Python can someone please help?

I'm also new to Python. I'm running the script on an Ubuntu 20 Linux install and have no issue right now (modifying the lines like the mentioned post say).

**Comment by Monsterbacke007** [comment] 2020-10-06 16:02
Is there a way to retry aborted or skipped files with filename? Havent found it in the doc.

**Comment by menkej** [comment] 2020-10-06 18:05
Guys, are you sure you're running the latest version of pyicloud-ipd? Please check:

`$ pip3 list | grep pyicloud-ipd`
`pyicloud-ipd      0.10.1`

If you are running an older version, please install the latest version of icloud_photos_downloader and the requirements.

`$ pip3 install -r requirements.txt`

It should not be necessary to edit files any more as the fix for the other bug is included now.

Is the issue still occurring?

**Comment by menkej** [comment] 2020-10-06 18:07
> Is there a way to retry aborted or skipped files with filename? Havent found it in the doc.

What do you mean? An selective download of a specific file? If you want to retry for whatever reason you could just rerun the script. Existing files are skipped quite quickly.

**Comment by Monsterbacke007** [comment] 2020-10-06 19:36
> > Is there a way to retry aborted or skipped files with filename? Havent found it in the doc.
> 
> What do you mean? An selective download of a specific file? If you want to retry for whatever reason you could just rerun the script. Existing files are skipped quite quickly.

All good. It seems the files were all downloaded despite the error. The only explanation I can imagine is that files were downloaded twice in a short amount of time so whilst file abc was written the system tried to write another instance of the exact same file and hence skipped it. Thx for all your feedbacks.

**Comment by konradorlinski** [comment] 2020-10-16 22:08
I had same issue on Debian 10. My solution is to create new directory and set chown for user which runs icloudpd. 
Long story short: icloudpd script don't have permissions to save in directory

**Comment by boredazfcuk** [comment] 2020-10-18 22:39
I've seen this issue tonight as well. A snippet from one of my logs:
```
2020-10-18 21:11:23 INFO     Downloading /home/user/iCloud/2020/98c430b4-11c0-4c31-915d-2fb82d459e0f.mp4
2020-10-18 21:11:25 INFO     Downloading /home/user/iCloud/2020/IMG_1294.PNG
2020-10-18 21:11:25 INFO     Downloading /home/user/iCloud/2020/IMG_1294.PNG
2020-10-18 21:11:26 INFO     Downloading /home/user/iCloud/2020/6bbdd713860347b46f5af9f424b4f5b8.jpg
2020-10-18 21:11:26 INFO     Downloading /home/user/iCloud/2020/IMG_1291.HEIC
2020-10-18 21:11:26 ERROR    IOError while writing file to /home/user/iCloud/2020/IMG_1294.PNG! You might have run out of disk space, or the file might be too large for your OS. Skipping this file...
2020-10-18 21:11:26 INFO     Downloading /home/user/iCloud/2020/IMG_1290.HEIC
2020-10-18 21:11:27 INFO     Downloading /home/user/iCloud/2020/IMG_1289.HEIC
...

2020-10-18 21:16:04 INFO     Downloading /home/user/iCloud/2020/IMG_0883.HEIC
2020-10-18 21:16:05 INFO     Downloading /home/user/iCloud/2020/IMG_0878.HEIC
2020-10-18 21:16:05 INFO     /home/user/iCloud/2020/camphoto_1804928587-3140301.jpg deduplicated.
2020-10-18 21:16:05 INFO     Downloading /home/user/iCloud/2020/camphoto_1804928587-3140301.jpg
2020-10-18 21:16:21 INFO     Downloading /home/user/iCloud/2020/IMG_0825.HEIC
2020-10-18 21:16:21 INFO     Downloading /home/user/iCloud/2020/IMG_0792.JPG
2020-10-18 21:16:22 INFO     Downloading /home/user/iCloud/2020/IMG_0791.HEIC
2020-10-18 21:16:22 INFO     Downloading /home/user/iCloud/2020/IMG_0790.HEIC
2020-10-18 21:16:23 ERROR    IOError while writing file to /home/user/iCloud/2020/camphoto_1804928587.jpg! You might have run out of disk space, or the file might be too large for your OS. Skipping this file...
2020-10-18 21:16:23 INFO     /home/user/iCloud/2020/camphoto_1804928587-3710764.jpg deduplicated.
2020-10-18 21:16:23 INFO     Downloading /home/user/iCloud/2020/camphoto_1804928587-3710764.jpg
2020-10-18 21:16:23 INFO     /home/user/iCloud/2020/camphoto_1804928587-3561146.jpg deduplicated.
2020-10-18 21:16:23 INFO     Downloading /home/user/iCloud/2020/camphoto_1804928587-3561146.jpg
2020-10-18 21:16:24 INFO     Downloading /home/user/iCloud/2020/IMG_0774.HEIC
2020-10-18 21:16:24 INFO     Downloading /home/user/iCloud/2020/IMG_0773.HEIC
2020-10-18 21:31:00 INFO     /home/user/iCloud/2020/camphoto_959030623.jpg already exists.
2020-10-18 21:31:00 INFO     /home/user/iCloud/2020/camphoto_1804928587.jpg already exists.
2020-10-18 21:31:00 INFO     /home/user/iCloud/2020/IMG_1267.HEIC already exists.
```

I think it may be related to multi-threaded downloads, as I haven't seen the error when using the `--threads-num 1` option, and I've downloaded my entire library multiple times tonight.

**Comment by AndreyNikiforov** [comment] 2020-10-28 14:28
> Is there a way to retry aborted or skipped files with filename? Havent found it in the doc.

Latest version of icloudpd download files with `.part` extension and rename only once download completes. Next time you run icloudpd all aborted files (with .part extension) will be re-downloaded. There is no support for resuming downloads.

There is no functionality to retry specific file, icloudpd will retry all aborted files. Latest version 1.6.2 encourages to use only one download thread and later versions will remove multithreaded downloading, so you should have at most one aborted file.

**Comment by AndreyNikiforov** [comment] 2020-10-28 14:31
@HarrisonOates @nihelmasell @Monsterbacke007 Do you still experience the issue with icloudpd 1.6.2 and `--threads-num 1`

**Comment by nihelmasell** [comment] 2020-10-29 00:00
> @HarrisonOates @nihelmasell @Monsterbacke007 Do you still experience the issue with icloudpd 1.6.2 and `--threads-num 1`

I didn't try it yet. What's the problem with the solution I used? Is it actually NOT downloading all iCloud files? I don't want to fix something that seems to work OK so far.

**Comment by AndreyNikiforov** [comment] 2020-10-29 17:04
> > @HarrisonOates @nihelmasell @Monsterbacke007 Do you still experience the issue with icloudpd 1.6.2 and `--threads-num 1`
> 
> I didn't try it yet. What's the problem with the solution I used? Is it actually NOT downloading all iCloud files? I don't want to fix something that seems to work OK so far.

@nihelmasell The solution you mentioned seems to be related to encoding. I saw such encoding error once and it was a different message from the one in this issue. IOError has been happening due to multi-threaded downloading, which has been changed to 1 by default in 1.6.2.

If you do not see IOError any more, I'll close the issue.

**Closed by AndreyNikiforov** 2020-10-29 17:04 UTC

**Comment by willytylee** [comment] 2023-05-30 08:05
I chmod -R to my NAS icloud folder to 755, and the error passed.
