### ISSUE TITLE
publish source tarball to pypi?

### ISSUE THREAD

**Issue by chenrui333** [icloud-photos-downloader/icloud_photos_downloader#811] opened 2024-04-11 01:06 UTC
👋 can you also publish the source tarball to pypi for package manager to consume? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/168596

**Comment by AndreyNikiforov** [comment] 2024-04-11 01:23
<img width="845" alt="Screenshot 2024-04-10 at 6 19 14 PM" src="https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/158558/d9a3be2c-acb4-4ac4-a3e7-11bb890c7d02">

It is there (icloudpd-1.17.4-py3-none-any.whl). You mos likely want to use default pip behavior that will download binary if it exists for the platform and fall back to src if needed. We have macos binary in pypi as well (icloudpd-1.17.4-py2.py3-none-macosx_11_0_x86_64.macosx_11_0_arm64.whl)

**Comment by chenrui333** [comment] 2024-04-11 01:34
yeah, those are all wheels, I am looking for the source tarball 

![image](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/1580956/9d69d558-4c57-468c-a37e-cebeaa36052b)

**Comment by AndreyNikiforov** [comment] 2024-04-11 01:52
I don't think we ever provided src to pypi, only wheels. Src is available in github though:
<img width="571" alt="Screenshot 2024-04-10 at 6 46 51 PM" src="https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/158558/5007d669-f455-4713-a2a6-5607dc9ad9b7">

Looking at the PR for homebrew, it seems that src from github were used before.

Is there any particular reason you want to use src, not binaries? Any reason you want zipped src vs wheels?

**Comment by chenrui333** [comment] 2024-04-11 15:38
> Looking at the PR for homebrew, it seems that src from github were used before.

yeah, the problem with github artifact is we dont have any mechanism to populate the dependency list.

**Comment by chenrui333** [comment] 2024-04-11 18:53
> Figuring out dependencies is challenging. We had a lot of issues reported related to dependencies until we switched to binary distribution.

that is interesting, any pointer on that (sounds like requirements list issue?)

**Comment by chenrui333** [comment] 2024-04-11 18:53
> BTW the failure in homebrew PR is in test expectation and icloudpd seems to be installed and running fine.

yeah, just updated the test to ship this release.

**Comment by chenrui333** [comment] 2024-05-23 21:58
relates to https://github.com/Homebrew/homebrew-core/pull/172656

**Comment by AndreyNikiforov** [comment] 2024-05-23 22:58
> relates to [Homebrew/homebrew-core#172656](https://github.com/Homebrew/homebrew-core/pull/172656)

What is the trigger for HB version bump? Should be github release IMO, and it is not yet available for v1.17.6.

**Comment by chenrui333** [comment] 2024-05-25 12:27
> What is the trigger for HB version bump? 

there is autobump process that we are using.

**Comment by chenrui333** [comment] 2024-05-25 12:28
same deal as this one, https://github.com/Homebrew/homebrew-core/pull/172797

**Comment by AndreyNikiforov** [comment] 2024-05-25 15:48
> same deal as this one, [Homebrew/homebrew-core#172797](https://github.com/Homebrew/homebrew-core/pull/172797)

What is the problem with this one? Seems to merged already.

**Comment by AndreyNikiforov** [comment] 2024-05-25 15:50
> > What is the trigger for HB version bump?
> 
> there is autobump process that we are using.

I suspect that autobump checks repository for changes and pulls sources from GH release. It takes hr+ to build and publish `icloudpd`, so to avoid problems in future, it would be best for you to adjust autobump process to use GH releases instead of source code changes.

**Comment by AndreyNikiforov** [comment] 2024-05-29 22:38
closing as the issue is related to how homebrew detects changes

**Closed by AndreyNikiforov** 2024-05-29 22:38 UTC
