### ISSUE TITLE
KeyError: 'filenameEnc'

### ISSUE THREAD

**Issue by ketz** [icloud-photos-downloader/icloud_photos_downloader#114] opened 2018-11-23 11:27 UTC
First of all, thanks a lot for creating this awesome script. It's proving massively useful already.

It got to 85% of all my photos and videos, and then I got this error:

```
Traceback (most recent call last):
  File "c:\users\ketz\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ketz\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ketz\AppData\Local\Programs\Python\Python37-32\Scripts\icloudpd.exe\__main__.py", line 9, in <module>
  File "c:\users\ketz\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ketz\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\ketz\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ketz\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ketz\appdata\local\programs\python\python37-32\lib\site-packages\icloudpd\base.py", line 349, in main
    if size not in photo.versions and size != "original":
  File "c:\users\ketz\appdata\local\programs\python\python37-32\lib\site-packages\pyicloud_ipd\services\photos.py", line 530, in versions
    version = {'filename': self.filename}
  File "c:\users\ketz\appdata\local\programs\python\python37-32\lib\site-packages\pyicloud_ipd\services\photos.py", line 473, in filename
    self._master_record['fields']['filenameEnc']['value']
KeyError: 'filenameEnc'
```

I've tried running it again a few times, but it always crashes in the same spot. 
Any chance you know what's causing it?

**Comment by ndbroadbent** [comment] 2018-11-23 13:19
Hi @ketz, thanks for reporting this issue! I haven't seen that one before. 

It looks like the "filenameEnc" attribute is missing, so maybe iCloud doesn't have a filename for that photo, or they've renamed the attribute to something else.

I need some more information to properly debug this issue, so what I've done is I've added an error handler to catch the `KeyError`, and then I'm saving the photo record as as JSON file. The script will print an error asking you to upload that photo record as a Gist, so I can see all the fields and fix the issue. (But you can also just paste the JSON here as a comment.)


Please run the following to update the `icloudpd` package to `1.3.5`:

```
pip uninstall -y icloudpd
pip install icloudpd==1.3.5
```

Then when you re-run the script, you should see the following error message:

```
KeyError: 'filenameEnc' attribute was not found in the photo fields!
icloudpd has saved the photo record to: ./icloudpd-photo-error.json
Please create a Gist with the contents of this file: https://gist.github.com
Then create an issue on GitHub: https://github.com/ndbroadbent/icloud_photos_downloader/issues
Include a link to the Gist in your issue, so that we can see what went wrong.
```

It will actually just skip this photo and keep going. But after it finishes, you should see a `icloudpd-photo-error.json` file in the same directory, so please paste that in here and I can take a look. Thanks!

**Comment by ketz** [comment] 2018-11-23 14:46
Thanks for that. Here you go:

`{  
   "itemType":{  
      "value":"public.jpeg",
      "type":"STRING"
   },
   "resJPEGThumbFingerprint":{  
      "value":"ASLUnD9lDEfQQz1o3dBztmXuoAbE",
      "type":"STRING"
   },
   "isExpunged":{  
      "value":0,
      "type":"INT64"
   },
   "resJPEGMedRes":{  
      "value":{  
         "fileChecksum":"ATLuuwfgKVHPzLr5DWLJqge5ao04",
         "size":700959,
         "wrappingKey":"NYNoUWQr8pfD1Nif7Vh7+A==",
         "referenceChecksum":"AaXmo93NRlGfnBZ6Boj+4jIYR8wU",
         "downloadURL":"https://cvws.icloud-content.com/B/ATLuuwfgKVHPzLr5DWLJqge5ao04AaXmo93NRlGfnBZ6Boj-4jIYdddddU/${f}?o=AsjFVuxkYU7Kl02S6wpUw_6ONgfCwWwAJ4BW5DaEzhAL&v=1&x=3&a=B8BWUfZxSkxmyw5dfBXlfqVjaQdpA69hRwEAAANzYUc&e=1542987729&k=NYNoUWQr8pfD1Nif7Vh7-A&fl=&r=9310c129-cee3-4243-86ce-566c9f932ad1-1&ckc=com.apple.photos.cloud&ckz=PrimarySync&y=1&p=34&s=7hW7eO7Gao1OIc-stkrMYKJldeo"
      },
      "type":"ASSETID"
   },
   "originalOrientation":{  
      "value":1,
      "type":"INT64"
   },
   "resJPEGMedHeight":{  
      "value":1532,
      "type":"INT64"
   },
   "resOriginalRes":{  
      "value":{  
         "fileChecksum":"AdfZTZX7YGVkmGH24ttI6PaE4iSY",
         "size":1462618,
         "wrappingKey":"BpplHsptZtm2Al+9n5kNFg==",
         "referenceChecksum":"AQJstmWWceKqnIErbkuI8/iGO/Lf",
         "downloadURL":"https://cvws.icloud-content.com/B/AdfZTZX7YGVkmGH24ttI6PaE4iSYAQJstmWWceKqnIErDEsfdsbkuI8_iGO_Lf/${f}?o=AkGao1HzdJzJgVjUYiU24PVQiG0oMe4cidhUb613yQVY&v=1&x=3&a=Bw-cr6moWo0jT4xCwXBOVwrvbqulA69hRwEAAANzYUc&e=1542987729&k=BpplHsptZtm2Al-9n5kNFg&fl=&r=9310c129-cee3-4243-86ce-566c9f932ad1-1&ckc=com.apple.photos.cloud&ckz=PrimarySync&y=1&p=34&s=VajXckUZ5pWJXN8FdHMJnLmuRJw"
      },
      "type":"ASSETID"
   },
   "resJPEGMedFileType":{  
      "value":"public.jpeg",
      "type":"STRING"
   },
   "resJPEGThumbHeight":{  
      "value":358,
      "type":"INT64"
   },
   "resJPEGThumbWidth":{  
      "value":480,
      "type":"INT64"
   },
   "resOriginalWidth":{  
      "value":2592,
      "type":"INT64"
   },
   "resJPEGThumbFileType":{  
      "value":"public.jpeg",
      "type":"STRING"
   },
   "dataClassType":{  
      "value":1,
      "type":"INT64"
   },
   "resOriginalFingerprint":{  
      "value":"AdfZTZX7YGVkmGH24ttI6PaE4iSY",
      "type":"STRING"
   },
   "resJPEGMedWidth":{  
      "value":2052,
      "type":"INT64"
   },
   "resJPEGThumbRes":{  
      "value":{  
         "fileChecksum":"ASLUnD9lDEfQQz1o3dBztmXuoAbE",
         "size":35461,
         "wrappingKey":"3E/wFKdF5mhxXfENObbOIg==",
         "referenceChecksum":"Adz344JhLz05j3+/vzPL7++MgoGF",
         "downloadURL":"https://cvws.icloud-content.com/B/ASLUnD9lDEfQQz1o3dBztmXuoAbEAdz344JhLz05j3-_vDasdzPL7--MgoGF/${f}?o=AhpC70WatRkdOwoEhfYu5neBe13DEdQ3TYUwDQpVFfZL&v=1&x=3&a=B_YzEMkZMDWc0rlINBKqOg8SdGcuA69hRwEAAANzYUc&e=1542987729&k=3E_wFKdF5mhxXfENObbOIg&fl=&r=9310c129-cee3-4243-86ce-566c9f932ad1-1&ckc=com.apple.photos.cloud&ckz=PrimarySync&y=1&p=34&s=kicFinEaf5dsK2GHpeFqQ4JWj0o"
      },
      "type":"ASSETID"
   },
   "resOriginalFileType":{  
      "value":"public.jpeg",
      "type":"STRING"
   },
   "resOriginalHeight":{  
      "value":1936,
      "type":"INT64"
   },
   "resJPEGMedFingerprint":{  
      "value":"ATLuuwfgKVHPzLr5DWLJqge5ao04",
      "type":"STRING"
   }
}`

**Comment by ndbroadbent** [comment] 2018-11-23 15:10
Thanks very much!

Really sorry about this, but unfortunately I didn't dump enough information about the photo. This output just confirmed that the `filenameEnc` key is missing, but it doesn't really tell me anything else.

If you wouldn't mind trying one more time, I've just released version `1.3.6`. This time it will dump both the "master record" and the "asset record", which should give me enough information to figure this out. (The "asset record" just contained the date before, but maybe they moved the filename in there as well.)

```
pip uninstall -y icloudpd
pip --no-cache-dir install icloudpd==1.3.6
```

Thanks a lot for your help! After this round, I'll have enough information to either fix the filename field, generate a new name based on the date, or just ignore the photo.

**Comment by ketz** [comment] 2018-11-27 14:34
Thanks for the update. 
Here's the latest output: https://gist.github.com/ketz/43e3a2c622f1591e9a295efd00e54eba

However, in the command prompt there are pages and pages of the error showing:
https://imgur.com/a/wiXEBB4
which doesn't seem to correspond to the little data shown in the json. Perhaps it's getting overwritten with every new occurrence, rather than adding to it?

Cheers

**Comment by ndbroadbent** [comment] 2018-11-27 17:40
Hi @ketz, thanks a lot! And sorry about all the pages of errors, you're right that I was just overwriting the one file. (I figured I just needed one example, and then I should be able to fix them all.)

But it's so strange that your photo data doesn't include any filename. Do you have any idea why that might have happened? iOS always adds an `IMG_****.JPG` filename when you take a photo with the camera. Same for screenshots. And I've seen some cases where old photo libraries are merged and synced up to iCloud. Or maybe it's one of your apps that is not setting a filename correctly.

Anyway, what I've decided to do is to just use the file "checksum" from the original photo. This is also what Apple is using as the master "record name". I was thinking about be saving these photos as "AdfZTZX7YGVkmGH24ttI6PaE4iSY.JPG". But 28 characters is probably overkill, especially because we are saving them in separate directories with `<year>/<month>/<day>`. So I think I'll truncate this to 12 characters, and the photo will be saved at: `2014/08/03/AdfZTZX7YGVk.JPG`

I think that should work. I'll start working on that now and will let you know when it's ready to test. Thanks for your help!

**Closed as completed** 2018-11-27 18:28 UTC
