### ISSUE TITLE
import Callable failure

### ISSUE THREAD

**Issue by jaxily** [icloud-photos-downloader/icloud_photos_downloader#499] opened 2022-11-15 22:19 UTC
Having issues just starting due to dependencies.  Please let me know how I can fix this.

Traceback (most recent call last):
  File "/Volumes/BigBackup/IcloudDB/icloud_photos_downloader/icloudpd/../icloudpd.py", line 2, in <module>
    from icloudpd.base import main
  File "/Volumes/BigBackup/IcloudDB/icloud_photos_downloader/icloudpd/base.py", line 17, in <module>
    from pyicloud_ipd.exceptions import PyiCloudAPIResponseError
  File "/usr/local/lib/python3.10/site-packages/pyicloud_ipd/__init__.py", line 2, in <module>
    from pyicloud_ipd.base import PyiCloudService
  File "/usr/local/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 19, in <module>
    from pyicloud_ipd.services import (
  File "/usr/local/lib/python3.10/site-packages/pyicloud_ipd/services/__init__.py", line 7, in <module>
    from pyicloud_ipd.services.account import AccountService
  File "/usr/local/lib/python3.10/site-packages/pyicloud_ipd/services/account.py", line 5, in <module>
    from pyicloud_ipd.utils import underscore_to_camelcase
  File "/usr/local/lib/python3.10/site-packages/pyicloud_ipd/utils.py", line 2, in <module>
    import keyring
  File "/usr/local/lib/python3.10/site-packages/keyring/__init__.py", line 6, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/local/lib/python3.10/site-packages/keyring/core.py", line 14, in <module>
    from . import backend
  File "/usr/local/lib/python3.10/site-packages/keyring/backend.py", line 18, in <module>
    from .util import properties
  File "/usr/local/lib/python3.10/site-packages/keyring/util/properties.py", line 1, in <module>
    from collections import Callable

**Comment by NafetsPB** [comment] 2022-11-19 15:46
This might be a duplicate of #435 if I'm not mistaken. I ran into the same issue just now and fixed it by upgrading the keyring as described in the referenced issue:

`$ pip install --upgrade keyring`

After that it worked immediately.

**Comment by jaxily** [comment] 2022-11-19 18:00
Amazing, you are right!  Thank you and have a great day!

**Closed** 2023-02-04 01:04 UTC
Labels: bug
