### ISSUE TITLE
Duplicate Photos do not download - same filename

### ISSUE THREAD

**Issue by realtek2017** [icloud-photos-downloader/icloud_photos_downloader#154] opened 2020-06-11 08:57 UTC
After spending months trying to work out why downloading my Photos iCloud Library on any device had a huge difference in photo count to iCloud.com (Difference of 3,000).

The issue is that on a lot of devices, if the upload does not complete successfully (or at least the device believes that) then you can end up with duplicate photos stored in iCloud.

This is not the problem but the problem is when exporting them. All tools I have used, stores the file when downloading using a folder structure in some combination of yyyy, mm, dd and finally the filename - The same issue accross iCloud for Windows, Photos for Mac, Even after asking Apple to export and supply all the data in iCloud, and even this project

If there are duplicates in iCloud, then the same filename cannot exist more than once on the local filesystem - so the tool (Including this one) overwrites the same file.

This will result in a big difference between total photo count.

My suggestion would be to implement a 'allow-duplicates' parameter which adds the current photo number at the end of the filename (or is there a unique id somewhere?)

Now there is a question as to whether duplicates 'need' to be downloaded people won't care about duplicates but I think the option should exist in case the users wants  to validate themselves.

**Comment by AndreyNikiforov** [comment] 2020-08-11 17:38
Adjusted code to use the size in addition to the name in asset comparisons: https://github.com/ndbroadbent/icloud_photos_downloader/pull/160

**Comment by AndreyNikiforov** [comment] 2020-10-09 04:22
@realtek2017 do you still see an issue with latest version of icloudpd?

**Comment by realtek2017** [comment] 2020-10-15 17:56
@AndreyNikiforov yes I get the same issue, I have just updated.

I believe for some reason iCloud does indeed store duplicates, and I mean the same filename, same date and possibly same filename/CRC/Binary etc... so identical file for whatever reason.

But, icloudpd should allow you to download these. I believe the files get skipped because they already exist. Could we add a command line option to rename if they already exist?

For example, I have 43509 photos in my iCloud library, but about 800 are missing after a complete download with icloudpd. I get the same issue with other applications. I have proved it by allowing these other applications to 'rename' if it exists - and then I end up with a complete match. But those products have other issues, so really would love this to be fixed in icloud pd.

**Comment by realtek2017** [comment] 2020-10-15 17:58
> @AndreyNikiforov yes I get the same issue, I have just updated.
> 
> I believe for some reason iCloud does indeed store duplicates, and I mean the same filename, same date and possibly same filename/CRC/Binary etc... so identical file for whatever reason.
> 
> But, icloudpd should allow you to download these. I believe the files get skipped because they already exist. Could we add a command line option to rename if they already exist?
> 
> For example, I have 43509 photos in my iCloud library, but about 800 are missing after a complete download with icloudpd. I get the same issue with other applications. I have proved it by allowing these other applications to 'rename' if it exists - and then I end up with a complete match. But those products have other issues, so really would love this to be fixed in icloud pd.

As another way of identifying the issue, I requested an export from Apple for my photo data. I compared the binary's I was sent with along with the CSV metadata information they provide. The CSV contained duplicate enteries, but the binary's were short of the same amount approx 800. This to me says the destination file system during the export is incapable of renaming the files if duplicates appear, and skip them. But the iCloud backend database does allow for this.

**Comment by menkej** [comment] 2020-10-16 18:43
> But, icloudpd should allow you to download these. I believe the files get skipped because they already exist. Could we add a command line option to rename if they already exist?

I'm just wondering how icloudpd should really behave with such a command line option? To really identify an identical file it must be downloaded n times, just to know: "this is duplicate, I save it under a different name "photo.jpg_2/3/4/..." What would be the benefit? No saving of bandwidth, no "new information" as the very same picture is already there, etc.

Just one Idea where this might come from: you can put your pictures into albums. One picture can be put into n albums, ergo n times to download maybe if you go for "All Photos" album...

**Comment by AndreyNikiforov** [comment] 2020-10-18 16:02
@realtek2017 If Apple indeed allows complete duplicates (name, size, content, other metadata), then what is the reason you need more than one copy of it locally (and how would you expect to differentiate them)? Does Apple show multiple copies in their UI?

If files have the same name, same content, but different size, then icloudpd 1.6.1+ will have them on your disk separate. If files are exactly the same and iCloud API exposes them without de-duping, then icloudpd 1.6.1+ will have only one copy of your disk and skip the rest as duplicates. If you see other behavior in icloudpd 1.6.1+, I could think of possible concurrency issue -- try `--threads-num=1`

**Comment by boredazfcuk** [comment] 2020-10-18 16:39
> Does Apple show multiple copies in their UI?

I have synchronised files using the Windows Store iCloud app so can answer this.

Files that iCloudPD detects as duplicates and saves with -<filesize> appended to the name. These files are saved by the iCloud app as camphoto_1234.JPG, camphoto_1234(1).JPG, camphoto_1234(2).JPG, camphoto_1234(3).JPG etc.

However, these files are named differently on my iPhone's filesystem... They have names like:
```
KMLY4906.JPG
MFCP3146.JPG
FDFE0501.JPG
```
All these files were photos taken in the Telegram messaging app.

**Comment by AndreyNikiforov** [comment] 2020-10-23 04:46
> > Does Apple show multiple copies in their UI?
> 
> I have synchronised files using the Windows Store iCloud app so can answer this.
> 
> Files that iCloudPD detects as duplicates and saves with - appended to the name. These files are saved by the iCloud app as camphoto_1234.JPG, camphoto_1234(1).JPG, camphoto_1234(2).JPG, camphoto_1234(3).JPG etc.
> 
> However, these files are named differently on my iPhone's filesystem... They have names like:
> 
> ```
> KMLY4906.JPG
> MFCP3146.JPG
> FDFE0501.JPG
> ```
> 
> All these files were photos taken in the Telegram messaging app.

@boredazfcuk in your example all three files have the same name and same size, correct? If correct, I assume they have same content/image and same metadata (at least date). I expect icloudpd to download only one instance of the file and report the other two as duplicate (and skip). Can you confirm that it is indeed the situation?

I personally do not see much value having three absolutely identical files on the disk, but would love to hear other opinions (somebody may expect to have _exact_ copy of iCloud). If the use case of having multiple copies of the same file needs to be supported, we'll have to follow approach similar to iPhone filesystem -- add an internal id (if such is exposed in API) to the file name.

**Comment by menkej** [comment] 2020-10-23 07:34
> I personally do not see much value having three absolutely identical files on the disk

I agree on that. It makes no real sense to save the same content multiple times (wast of space) and maybe later use some other tool to get rid of duplicates even (didn't we even have a feature request for that?) This is especially true when you use the standard folder structure (by date).

The only case I can think of where it makes sense to store a file multiple times is when you would use the album names as folder structure (which is not possible yet, I think), as you can have the same picture in multiple albums...

**Comment by boredazfcuk** [comment] 2020-10-23 11:31
> @boredazfcuk in your example all three files have the same name and same size, correct? If correct, I assume they have same content/image and same metadata (at least date). I expect icloudpd to download only one instance of the file and report the other two as duplicate (and skip). Can you confirm that it is indeed the situation?

No, all files are different. Significantly different too. Taken months apart, size differences of about 1MB. 

This is how they display in my Windows VM's iCloud folder: https://imgur.com/a/hmsyIzr
But this is how they look on my laptop with my iPhone connected via USB: https://imgur.com/a/J9UtQNC

> I personally do not see much value having three absolutely identical files on the disk, but would love to hear other opinions (somebody may expect to have _exact_ copy of iCloud). If the use case of having multiple copies of the same file needs to be supported, we'll have to follow approach similar to iPhone filesystem -- add an internal id (if such is exposed in API) to the file name.

I think an exact replica would be the holy grail, but I'm not sure it would be feasible. The filenames used on my phone are different to the names stored in iCloud. There has to be a DB somewhere of which file on my phone relates to which file in iCloud, and without access to that DB, you're going to struggle.

Personally I'm happy with this only downloading the files that reside in the main Photo Stream. I don't organise anything into folder/albums until the pictures hit my SAN.

**Comment by AndreyNikiforov** [comment] 2020-10-23 15:37
> > @boredazfcuk in your example all three files have the same name and same size, correct? If correct, I assume they have same content/image and same metadata (at least date). I expect icloudpd to download only one instance of the file and report the other two as duplicate (and skip). Can you confirm that it is indeed the situation?
> 
> No, all files are different. Significantly different too. Taken months apart, size differences of about 1MB.

I expect icloudpd 1.6.2 to download three files: img_1234.jpg, img_1234-456.jpg, and img_1234-789.jpg, where `456` and `789` are sizes of the second and third images in iCloud. If you use `--set-exif-datetime` and your files do not have exit datetime, then sizes on your disk will be different from `456` and `789`. @boredazfcuk is this happening?

@realtek2017 do you still experience missing files with icloudpd 1.6.2+? I would love to understand how we can reproduce and fix the issue or close it if it is fixed.

**Comment by boredazfcuk** [comment] 2020-10-24 18:37
Yes, I it is correctly downloading files.

I'm just documenting the differences between what I see on my phone from what is stored in iCloud. That is, files with different names on my iPhone end up having identical names on iCloud.

**Comment by AndreyNikiforov** [comment] 2020-10-28 00:46
Closing. Feel free to reopen if issue persists.

**Closed by AndreyNikiforov** 2020-10-28 00:46 UTC

**Comment by realtek2017** [comment] 2021-03-24 11:22
Hi @AndreyNikiforov

Sorry for the delay in responding. I am available to assist on this now.

I understand the need to not download duplicates as it does make sense because no one would want an exact duplicate photo.

However, my use case for such a feature is because for someone trying to backup their iCloud photos it is important for verification purposes that the total amount of photos downloaded would match the same number reported in iCloud and for that reason it would be great to have an option to allow duplicates.

I would suggest if the file exists on the local filesystem then it would be good to create the new file with a different name.

The issue I see in doing this is we will need to record this somewhere as I don't know how this could be handled if someone is also allowing deletions to occur when files exist in the 'Deleted Photos' folder, because it will not know which one could be the duplication and there may be other situations also.

For example, I have 55,520 photos in iCloud but after downloading them I end up getting 54,300 for example. There is a large shortfall, and from analysising the way iCloud for windows works and other exports using varios tools, I have pinned it down to the same filename existing in iCloud - even using a Apple data request to export the photos database gives me the same issue.

Even the CSV files Apple provide with the export include all filenames has duplicates in it. I compare the total number in the CSV files with the binaries I received and there is the same amount of shortfall.

I don't know why but iCloud allows for duplicates and these are included in the total Photo count, but the filesystem either skips or overwrites the duplicates when the name matches.

Thanks
