### ISSUE TITLE
cannot import name 'Callable' from 'collections'

### ISSUE THREAD

**Issue by MoLiYue** [icloud-photos-downloader/icloud_photos_downloader#402] opened 2022-01-01 01:26 UTC
I use python3.10 to install icloudpd, and after installing when I try to do some settings it reports this problem.

```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\icloudpd.exe\__main__.py", line 4, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\icloudpd\base.py", line 17, in <module>
    from pyicloud_ipd.exceptions import PyiCloudAPIResponseError
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pyicloud_ipd\__init__.py", line 2, in <module>
    from pyicloud_ipd.base import PyiCloudService
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pyicloud_ipd\base.py", line 19, in <module>
    from pyicloud_ipd.services import (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pyicloud_ipd\services\__init__.py", line 7, in <module>
    from pyicloud_ipd.services.account import AccountService
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pyicloud_ipd\services\account.py", line 5, in <module>
    from pyicloud_ipd.utils import underscore_to_camelcase
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pyicloud_ipd\utils.py", line 2, in <module>
    import keyring
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\keyring\__init__.py", line 6, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\keyring\core.py", line 14, in <module>
    from . import backend
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\keyring\backend.py", line 18, in <module>
    from .util import properties
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\keyring\util\properties.py", line 1, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)
```

**Comment by Toxsch** [comment] 2022-01-02 08:46
Encounter the same problem.
This is an upstream dependency issue. the required keyring in pyicloud_ipd is 8.7, but it is only supported on Python 3.5 and earlier version
Upgrade keyring can avoid this problem, but I didn't test detail

**Comment by menkej** [comment] 2022-02-06 20:44
There is still some work on making this compatible with python 3.10. And right, it is a duplicate of #390, so I close this one here.

**Closed by menkej** 2022-02-06 20:44 UTC
Labels: bug
