### ISSUE TITLE
Error that I don't understand. "private db access disabled for this account"

### ISSUE THREAD

**Issue by Potter3117** [icloud-photos-downloader/icloud_photos_downloader#796] opened 2024-02-28 12:20 UTC
## Overview
Installed from unraid community library. when running the command to start a sync it asked for and accepted my 2fa codes but gives me the following error.

pyicloud_ipd.exceptions.PyiCloudAPIResponseException: private db access disabled for this account.  Please wait a few minutes then try again.The remote servers might be trying to throttle requests. (ACCESS_DENIED)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start container
2. run _sync-icloud.sh --Initialise_ (it confirms my login is accepted when running this or the _sync-icloud.sh_ command)
3. get error

## Expected Behavior
I expected my icloud photos to start synchronizing

## Actual Behavior
I get the error pasted above and nothing happens.

## Context
This is run through the the UnRaid community docker container. I have manually created a .mounted file per the instructions in the library location and then followed all instructions to the letter after cross referencing this project in github and the details in the unraid community area for the docker container. I have set it to try again every 24 hours so maybe it will clear on it's own if I ignore it. I have a photo library of just over 40k items.

**Comment by aaron-trout** [comment] 2024-03-01 21:32
I am getting the same thing on MacOS, installed from HomeBrew.

```bash
$ icloudpd --directory=/Volumes/home/Photos/iCloud --username="<REDACTED>" --set-exif-datetime
2024-03-01 21:31:13 DEBUG    Authenticating...
iCloud Password:
2024-03-01 21:31:21 ERROR    private db access disabled for this account.  Please wait a few minutes then try again.The remote servers might be trying to throttle requests. (ACCESS_DENIED)
Traceback (most recent call last):
  File "/opt/homebrew/bin/icloudpd", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/icloudpd/1.17.3/libexec/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/icloudpd/1.17.3/libexec/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/icloudpd/1.17.3/libexec/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/icloudpd/1.17.3/libexec/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/icloudpd/1.17.3/libexec/lib/python3.12/site-packages/icloudpd/base.py", line 328, in main
    core(
  File "/opt/homebrew/Cellar/icloudpd/1.17.3/libexec/lib/python3.12/site-packages/icloudpd/base.py", line 790, in core
    library_object = icloud.photos
                     ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/icloudpd/1.17.3/libexec/lib/python3.12/site-packages/pyicloud_ipd/base.py", line 624, in photos
    self._photos = PhotosService(service_root, self.session, self.params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/icloudpd/1.17.3/libexec/lib/python3.12/site-packages/pyicloud_ipd/services/photos.py", line 254, in __init__
    super(PhotosService, self).__init__(
  File "/opt/homebrew/Cellar/icloudpd/1.17.3/libexec/lib/python3.12/site-packages/pyicloud_ipd/services/photos.py", line 154, in __init__
    request = self.service.session.post(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/icloudpd/1.17.3/libexec/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/icloudpd/1.17.3/libexec/lib/python3.12/site-packages/pyicloud_ipd/base.py", line 178, in request
    self._raise_error(code, reason)
  File "/opt/homebrew/Cellar/icloudpd/1.17.3/libexec/lib/python3.12/site-packages/pyicloud_ipd/base.py", line 207, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: private db access disabled for this account.  Please wait a few minutes then try again.The remote servers might be trying to throttle requests. (ACCESS_DENIED)
```

**Comment by aaron-trout** [comment] 2024-03-01 21:36
@Potter3117 I think this is because of the "advanced data protection" option in iCloud. This issue looks like a duplicate of https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/687 essentially

**Comment by AndreyNikiforov** [comment] 2024-05-29 22:41
`sync-icloud.sh` is not part of this repo. pls use another repo to file issues.

**Closed by AndreyNikiforov** 2024-05-29 22:41 UTC
Labels: bug

**Comment by machsix** [comment] 2024-08-18 03:24
It happened to me because I didn't enable "Access iCloud Data on the Web". It should be documented somewhere
